# Stage 10 - Feature Engineering

## Project

AI-Based Smart Factory Flow Optimizer

## Objective

Prepare the dataset for Machine Learning by creating new features.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/processed/cleaned_factory_flow_data.csv")

In [3]:
df.head()

,Product_ID,Machine_ID,Machine_Status,Queue_Length,Processing_Time,Worker_Available,Shift,Material_Type,Temperature,Previous_Wait_Time,Current_Wait_Time,Next_Machine,Recommended_Machine,Expected_Waiting_Time
0,P0112,Grinding_M2,Idle,6,33,No,Evening,Ceramic_Hybrid,39,12,12,Packaging_Line,Polishing_M3,29

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Product_ID             1 non-null      object
 1   Machine_ID             1 non-null      object
 2   Machine_Status         1 non-null      object
 3   Queue_Length           1 non-null      int64
 4   Processing_Time        1 non-null      int64
 5   Worker_Available       1 non-null      object
 6   Shift                  1 non-null      object
 7   Material_Type          1 non-null      object
 8   Temperature            1 non-null      int64
 9   Previous_Wait_Time     1 non-null      int64
 10  Current_Wait_Time      1 non-null      int64
 11  Next_Machine           1 non-null      object
 12  Recommended_Machine    1 non-null      object
 13  Expected_Waiting_Time  1 non-null      int64
dtypes: int64(6), object(8)
memory usage: 244.0+ bytes

In [5]:
df["Worker_Status"] = df["Worker_Available"].map({
    "Yes":1,
    "No":0
})

In [6]:
df[["Worker_Available","Worker_Status"]].head()

  Worker_Available  Worker_Status
0               No              0

## Observation

Worker availability has been converted into numerical values.

Yes = 1

No = 0

In [7]:
df["Machine_Load"] = df["Machine_Status"].map({
    "Idle":0,
    "Busy":1,
    "Maintenance":2,
    "Overloaded":3
})

In [8]:
df[["Machine_Status","Machine_Load"]].head()

  Machine_Status  Machine_Load
0           Idle             0

In [9]:
df["Shift_Code"] = df["Shift"].map({
    "Morning":0,
    "Afternoon":1,
    "Night":2
})

In [10]:
df[["Shift","Shift_Code"]].head()

     Shift  Shift_Code
0  Evening         NaN

In [11]:
def queue_category(q):

    if q < 5:
        return "Low"

    elif q < 15:
        return "Medium"

    else:
        return "High"

df["Queue_Category"] = df["Queue_Length"].apply(queue_category)

In [12]:
df["Queue_Category"].value_counts()

Queue_Category
Medium    1
Name: count, dtype: int64

In [13]:
def temp_level(t):

    if t < 50:
        return "Normal"

    elif t < 70:
        return "Warm"

    else:
        return "Hot"

df["Temperature_Level"] = df["Temperature"].apply(temp_level)

In [14]:
df["Temperature_Level"].value_counts()

Temperature_Level
Normal    1
Name: count, dtype: int64

In [15]:
df["Bottleneck_Flag"] = np.where(
    df["Queue_Length"] >= 15,
    1,
    0
)

In [16]:
df["Bottleneck_Flag"].value_counts()

Bottleneck_Flag
0    1
Name: count, dtype: int64

In [17]:
def delay_level(wait):

    if wait < 10:
        return "Low"

    elif wait < 20:
        return "Medium"

    else:
        return "High"

df["Delay_Level"] = df["Expected_Waiting_Time"].apply(delay_level)

In [18]:
df["Delay_Level"].value_counts()

Delay_Level
High    1
Name: count, dtype: int64

In [ ]:
df.head()

,Product_ID,Machine_ID,Machine_Status,Queue_Length,Processing_Time,Worker_Available,Shift,Material_Type,Temperature,Previous_Wait_Time,...,Next_Machine,Recommended_Machine,Expected_Waiting_Time,Worker_Status,Machine_Load,Shift_Code,Queue_Category,Temperature_Level,Bottleneck_Flag,Delay_Level
0,P0112,Grinding_M2,Idle,6,33,No,Evening,Ceramic_Hybrid,39,12,...,Packaging_Line,Polishing_M3,29,0,0,NaN,Medium,Normal,0,High

In [20]:
df.to_csv("../data/processed/final_factory_data.csv", index=False)

print("Feature Engineering Completed Successfully!")

Feature Engineering Completed Successfully!

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Product_ID             1 non-null      object
 1   Machine_ID             1 non-null      object
 2   Machine_Status         1 non-null      object
 3   Queue_Length           1 non-null      int64
 4   Processing_Time        1 non-null      int64
 5   Worker_Available       1 non-null      object
 6   Shift                  1 non-null      object
 7   Material_Type          1 non-null      object
 8   Temperature            1 non-null      int64
 9   Previous_Wait_Time     1 non-null      int64
 10  Current_Wait_Time      1 non-null      int64
 11  Next_Machine           1 non-null      object
 12  Recommended_Machine    1 non-null      object
 13  Expected_Waiting_Time  1 non-null      int64
 14  Worker_Status          1 non-null      int64
 15  Machine_Load           1 non-null      int64
 16  Shift_Code             0 non-null      float64
 17  Queue_Category         1 non-null      object
 18  Temperature_Level      1 non-null      object
 19  Bottleneck_Flag        1 non-null      int64
 20  Delay_Level            1 non-null      object
dtypes: float64(1), int64(9), object(11)
memory usage: 300.0+ bytes

# Conclusion

Feature Engineering was successfully completed.

New features were created from the original dataset to improve the performance of Machine Learning models.

The processed dataset is now ready for training:

- Random Forest Regressor (Expected Waiting Time Prediction)
- Random Forest Classifier (Best Machine Recommendation)